language: python
cache: pip
python:
  - 3.7


install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy


jobs:
  include:
    # Run tests, check coverage and report
    - stage: test
      script:
        - coverage run --source='.' -m pytest
        - coverage report -m
        - coveralls
    # Deploy code
    - stage: deploy
      script:
        - echo 'Deploy to Digitalocean'

stages:
  - name: test
  - name: deploy
    if: type = push AND branch = master
