language: python
cache: pip
python:
  - 3.7


install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy


jobs:
  include:
    # Run tests, check coverage and report
    - stage: lint
      script:
        - pylint_runner
    - stage: test
      script:
        - pytest  --cov='.' .
        - coverage report -m --fail-under=80
        - coveralls
    # Deploy code
    - stage: deploy
      script:
        - echo 'Deploy to Digitalocean'

stages:
  - name: lint
  - name: test
  - name: deploy
    if: type = push AND branch = master
