version: '3'

services:

  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - static_volume:/usr/src/dist/src/var/static
      - media_volume:/usr/src/dist/src/var/media
    depends_on:
      - django
    networks:
      - nginx_network

  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn src.core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/dist/src/var/static
      - media_volume:/usr/src/dist/src/var/media
    expose:
      - 8000
    env_file: ./conf/django/.env
    depends_on:
      - database
    networks:
      - nginx_network
      - database_network

  database:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file: ./conf/database/.env
    networks:
      - database_network


volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
